### ISSUE TITLE
Basic movement

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/ten-aod_animations#1]
This is the list of all animations that exist both in _TombEngine_ (based on _TR4: The Last Revelation_ and _TR5: Chronicles_) and _TR6: The Angel Of Darkness_. It is extracted from AOD's animation list.

Naturally, checked ones means they have been remade, others are yet to be done.

### Part 1: General ground movement
- [x] LARA_DEATH_RUN
- [x] LARA_DEATH_RUN_MIRROR
- [x] LARA_DEATH_STANCE
- [x] LARA_HITWALL_A
- [x] LARA_ROLL
- [x] LARA_ROLL_TO_STANCE
- [x] LARA_RUN
- [x] LARA_RUN_TO_RUNJUMP
- [x] LARA_RUN_TO_RUNJUMP_MIRROR
- [x] LARA_RUN_TO_STANCE
- [x] LARA_RUN_TO_STANCE_MIRROR
- [x] LARA_RUNJUMP
- [x] LARA_RUNJUMP_MIRROR
- [x] LARA_RUNJUMP_TO_RUN
- [x] LARA_RUNSTEPUP_QTR
- [x] LARA_RUNSTEPUP_QTR_MIRROR
- [x] LARA_SLIDE_BACK
- [x] LARA_SLIDE_BACK_LAND
- [x] LARA_SLIDE_FORWARD
- [x] LARA_SLIDE_FORWARD_LAND
- [x] LARA_SPRINT
- [x] LARA_STANCE
- [x] LARA_STANCE_TO_ROLL
- [x] LARA_STANCE_TO_RUN
- [x] LARA_STANCE_TO_WALK
- [x] LARA_STANCE_TURN45
- [x] LARA_STANCE_TURN45_MIRROR
- [x] LARA_STANCE_TURN90
- [x] LARA_STANCE_TURN90_END
- [x] LARA_STANCE_TURN90_END_MIRROR
- [x] LARA_STANCE_TURN90_MIRROR
- [x] LARA_STANCE_TURN90_START
- [x] LARA_STANCE_TURN90_START_MIRROR
- [x] LARA_STANCE_TURN180
- [x] LARA_STEP_SIDEB
- [x] LARA_STEP_SIDEB_MIRROR
- [x] LARA_STEPBACK
- [x] LARA_STEPBACK_START
- [x] LARA_STEPBACK_STOP
- [x] LARA_STEPBACK_STOPLEFT
- [ ] LARA_WAKE_UP
- [x] LARA_WALK
- [x] LARA_WALK_TO_STANCE
- [x] LARA_WALK_TO_STANCE_MIRROR
- [x] LARA_WALKSTEPDOWN_QTR
- [x] LARA_WALKSTEPDOWN_QTR_MIRROR
- [x] LARA_WALKSTEPUP_QTRBLK
- [x] LARA_WALKSTEPUP_QTRBLK_MIRROR

### Part 2: Jumping / falling
- [x] LARA_COMPRESS
- [x] LARA_COMPRESS_TO_JUMPB
- [x] LARA_COMPRESS_TO_JUMPF
- [x] LARA_COMPRESS_TO_JUMPFS
- [x] LARA_COMPRESS_TO_JUMPL
- [x] LARA_COMPRESS_TO_JUMPL_MIRROR
- [x] LARA_COMPRESS_TO_JUMPU
- [x] LARA_COOL_CLIMB
- [x] LARA_DETH_LAND
- [x] LARA_DIVE
- [x] LARA_DIVE_DEATH
- [x] LARA_DIVE_LAND
- [x] LARA_FALL
- [x] LARA_FAST_FALL
- [x] LARA_FAST_LAND
- [x] LARA_FASTDIVE
- [x] LARA_GRAB
- [x] LARA_JUMP_SPLAT
- [x] LARA_JUMPF
- [x] LARA_JUMPF_LAND
- [x] LARA_JUMPF_TO_FALLF
- [x] LARA_JUMPF_TO_REACH
- [x] LARA_JUMPL
- [x] LARA_JUMPL_MIRROR
- [x] LARA_JUMPU
- [x] LARA_JUMPU_LAND
- [x] LARA_SPRINTJUMP
- [x] LARA_SPRINTJUMP to LARA_REACH transitions (x4)
- [x] LARA_SPRINTJUMP_MIRROR
- [x] LARA_SPRINTJUMP_MIRROR to LARA_REACH transitions (x4)
- [x] LARA_SPRINTJUMP_START
- [x] LARA_SPRINTJUMP_START_MIRROR
- [x] LARA_VERTICAL_FALL

### Part 4: Water / water surface
- [x] LARA_SURFSWIM
- [x] LARA_SURFSWIM_BACK
- [ ] LARA_SURFSWIM_RIGHT
- [ ] LARA_SURFSWIM_RIGHT_MIRROR
- [x] LARA_SURFTREAD
- [x] LARA_SURFTREAD_TO_LEDGE8TH
- [x] LARA_SURFTREAD_TO_LEDGEQTR
- [x] LARA_SURFTREAD_TO_SWIM
- [x] LARA_SWIM
- [ ] LARA_SWIM_TO_WALLCLIMB
- [x] LARA_UNDERWATER_DEATH
- [x] LARA_UNDERWATER_TREAD
- [x] LARA_UNDERWATER_TURN180
- [x] LARA_WADE

### Part 5: Modern controls specific (not officially implemented yet)
- [x] LARA_SKIP_BACK
- [x] LARA_SKIP_BACK_START
- [x] LARA_SKIP_BACK_STOP
- [x] LARA_SKIP_BACK_STOP_EARLY (does not exist but needed for responsiveness)
