### ISSUE TITLE
Basic movement (TEN-specific)

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/ten-aod_animations#2]
This is the list of all animations that exist in _TombEngine_ (either from TR1 to TR5, or new moves specific to TEN), that don't exist in _TR6: The Angel Of Darkness_.
If an animation is not in the list, it means there is no plan to remake them.

Naturally, checked ones means they have been remade, others are yet to be done.

### Part 1: General ground movement
- [ ] Crawl backwards to hang
- [x] Crawlspace roll
- [x] Fall death (health loss, not high height)
- [x] Pose
- [ ] Rolling ball death
- [x] Run to crouch left
- [x] Run to crouch right
- [x] Slide forward to run
- [x] Sprint skid left
- [x] Sprint skid right
- [ ] Sprint roll left
- [ ] Sprint roll right
- [ ] Sprint roll to crouch left
- [ ] Sprint roll to crouch right
- [x] Stance to sprint
- [x] Stance to wade
- [x] Step back down left
- [x] Step back down right

### Part 2: Jumping / falling
- [x] Jump back to roll in air
- [x] Jump forward to roll in air
- [x] Dive roll to run

### Part 3: Water / water surface
- [x] Dive flip
- [x] Dive to swim (high height)
- [x] Dive to swim (small height)
- [x] Fast fall to swim
- [x] Run to wade left
- [x] Run to wade right
- [ ] Surface swim death
- [x] Surface swim to wade
- [x] Surface swim to stance (1 click pond)
- [ ] Surface swim to crouch (1 click step)
- [ ] Surface swim to crouch (0 click step)
- [ ] Surface swim to crouch (-1 click step)
- [ ] Surface swim turn 180
- [ ] Swim to stance (1 click pond)
- [x] Wade stop left
- [x] Wade stop right
- [x] Wade to run left
- [x] Wade to run right
