### ISSUE TITLE
Platforming

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/ten-aod_animations#3]
This is the list of all animations that exist both in _TombEngine_ (based on _TR4: The Last Revelation_ and _TR5: Chronicles_) and _TR6: The Angel Of Darkness_. It is extracted from AOD's animation list.

Naturally, checked ones means they have been remade, others are yet to be done.

### Part 1: Hanging on ledges / vaulting
- [ ] LARA_DEEP_GRAB
- [x] LARA_LEDGE_GRAB
- [x] LARA_REACH
- [x] LARA_REACH_TO_GRAB
- [x] LARA_SHIMMY
- [x] LARA_SHIMMY_CORNER_INSIDE
- [x] LARA_SHIMMY_CORNER_INSIDE_MIRROR
- [ ] LARA_SHIMMY_CORNER_OUTSIDE
- [ ] LARA_SHIMMY_CORNER_OUTSIDE_MIRROR
- [x] LARA_SHIMMY_MIRROR
- [x] LARA_STEPUP_HLFBLOCK
- [x] LARA_UP3QTRBLOCK
- [x] LARA_VAULT_A
- [x] LARA_WALL_JUMPUP

### Part 2: Wall climbing
- [ ] LARA_CLIMB_CORNER_INSIDE
- [ ] LARA_CLIMB_CORNER_INSIDE_MIRROR
- [x] LARA_CLIMB_CORNER_OUTSIDE
- [x] LARA_CLIMB_CORNER_OUTSIDE_MIRROR
- [x] LARA_HANG_TO_WALLCLIMBPOSE
- [x] LARA_STANCE_TO_WALLCLIMBPOSE
- [ ] LARA_SWIM_TO_WALLCLIMB
- [x] LARA_WALLCLIMB_LEFT
- [x] LARA_WALLCLIMB_TO_HANG (actually it's a new one, because she has to go down by a step while she doesn't in AOD)
- [x] LARA_WALLCLIMBDOWN
- [x] LARA_WALLCLIMBDOWN_START
- [x] LARA_WALLCLIMBDOWN_STOP
- [x] LARA_WALLCLIMBDOWN_STOP_MIRROR
- [x] LARA_WALLCLIMBPOSE
- [x] LARA_WALLCLIMBPOSE_ONLEDGE
- [x] LARA_WALLCLIMBSIDE
- [x] LARA_WALLCLIMBUP
- [x] LARA_WALLCLIMBUP_START
- [x] LARA_WALLCLIMBUP_STOP
- [x] LARA_WALLCLIMBUP_STOP_MIRROR
- [x] LARA_WALLCOMPRESS

### Part 3: Crouching / crawling
- [x] LARA_CRAWL_BACK
- [x] LARA_CRAWL_BACK_START
- [x] LARA_CRAWL_BACK_STOP
- [x] LARA_CRAWL_BACK_STOP_MIRROR
- [x] LARA_CRAWL_BREATH
- [x] LARA_CRAWL_DEATH
- [x] LARA_CRAWL_FORWARD
- [x] LARA_CRAWL_FORWARD_START
- [x] LARA_CRAWL_FORWARD_STOP
- [x] LARA_CRAWL_FORWARD_STOP_MIRROR
- [X] LARA_CRAWL_INTO_FALL
- [x] LARA_CRAWL_TURN45
- [x] LARA_CRAWL_TURN45_MIRROR
- [x] LARA_CRAWLPOSE_TO_CROUCH
- [x] LARA_CROUCH_BREATH
- [x] LARA_CROUCH_TAKE
- [x] LARA_CROUCH_TO_CRAWLPOSE
- [x] LARA_CROUCH_TO_STANCE
- [x] LARA_CROUCH_TURN45
- [x] LARA_CROUCH_TURN45_RIGHT
- [x] LARA_CROUCHHIT_BACK
- [x] LARA_CROUCHHIT_FRONT
- [ ] LARA_CROUCHHIT_LEFT
- [ ] LARA_CROUCHHIT_RIGHT
- [x] LARA_STANCE_TO_CROUCH
- [ ] LARA_VAULT_A to CROUCH (does not exist as a file but appears in-game)

### Part 4: Monkey swinging
- [x] LARA_MONKEY_FORWARD
- [x] LARA_MONKEY_HANG
- [ ] LARA_MONKEY_HANG_REVERSE
- [x] LARA_MONKEY_START
- [x] LARA_MONKEY_STOP
- [x] LARA_MONKEY_STOP_MIRROR
- [ ] LARA_MONKEY_TURN
- [ ] LARA_MONKEY_TURN_MIRROR
- [ ] LARA_MONKEY_TURN_START
- [ ] LARA_MONKEY_TURN_START_MIRROR
- [ ] LARA_MONKEY_TURN_STOP
- [ ] LARA_MONKEY_TURN_STOP_MIRROR
