### ISSUE TITLE
Platforming (TEN-specific)

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/ten-aod_animations#4]
This is the list of all animations that exist in _TombEngine_ (either from TR1 to TR5, or new moves specific to TEN), that don't exist in _TR6: The Angel Of Darkness_.
If an animation is not in the list, it means there is no plan to remake them.

Naturally, checked ones means they have been remade, others are yet to be done.

### Part 1: Hanging on ledges / vaulting
- [ ] Ledge corner left outer 45
- [ ] Ledge corner right outer 45
- [ ] Ledge corner left inner 45
- [ ] Ledge corner right inner 45
- [x] Ledge jump up
- [ ] Ledge jump back

### Part 2: Wall climbing
- [x] Wall climb dismount left
- [ ] Wall climb dismount right
- [x] Wall climb down with arms only
- [x] Wall climb up with arms only
- [x] Wall climb jump backwards
- [x] Wall climb to hang left
- [x] Wall climb to hang right
- [x] Wall climb to monkey overhead

### Part 3: Crouching / crawling
- [ ] Crouch turn 180
- [ ] Crawl turn 180
- [ ] Vault to crouch 1 step
- [ ] Vault to crouch 2 step
- [ ] Vault to crouch 3 step
- [ ] Crawl jump down 1 step
- [ ] Crawl jump down
- [ ] Crawl step up
- [ ] Crawl step down

### Part 4: Monkey swinging
- [x] Monkey grab from jump up
- [ ] Monkey shimmy left
- [ ] Monkey shimmy right
- [x] Monkey jump forward
