### ISSUE TITLE
Object interaction

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/ten-aod_animations#5]
This is the list of all animations that exist both in _TombEngine_ (based on _TR4: The Last Revelation_ and _TR5: Chronicles_) and _TR6: The Angel Of Darkness_. It is extracted from AOD's animation list.

Naturally, checked ones means they have been remade, others are yet to be done.

### Part 1: Weapons
- [x] LARA_AIM_GUN
- [x] LARA_AIM_GUN_LOOP
- [ ] LARA_AIM_MACHINEGUN
- [x] LARA_AIM_LOOP
- [ ] LARA_AIM_SHOTGUN
- [ ] LARA_AIM_SHOTGUN_LOOP
- [x] LARA_DRAW_GUN
- [ ] LARA_DRAW_MACHINEGUN
- [x] LARA_DRAW_PISTOLS
- [ ] LARA_DRAW_SHOTGUN
- [ ] LARA_HARPOON_DRAW (does not appear in-game)
- [ ] LARA_HARPOON_HOLSTER (does not appear in-game)
- [ ] LARA_HARPOON_SHOOT (does not appear in-game)
- [x] LARA_HOLSTER_GUN
- [x] LARA_HOLSTER_PISTOLS
- [ ] LARA_HOLSTER_SHOTGUN
- [ ] LARA_RELOAD_MACHINEGUN
- [ ] LARA_RELOAD_SHOTGUN
- [x] LARA_SHOOT_GUN
- [ ] LARA_SHOOT_MACHINEGUN
- [x] LARA_SHOOT_PISTOLS2
- [ ] LARA_SHOOT_SHOTGUN

### Part 2: Other object interaction
- [x] LARA_CHAIN_PULL
- [x] LARA_CHAIN_PULL_END
- [x] LARA_CHAIN_START
- [ ] LARA_DRAWER_*
- [x] LARA_ESWITCH_DOWN
- [x] LARA_ESWITCH_UP
- [x] LARA_KICK_DOOR_OPEN
- [ ] LARA_OPEN_CROWBAR
- [x] LARA_PICK_UP
- [ ] LARA_PICKUP_HIGH
- [x] LARA_PICKUP_MEDIUM
- [x] LARA_PULL_BLOCK_HALF
- [x] LARA_PULL_BLOCK_START
- [x] LARA_PULL_BLOCK_STOP
- [x] LARA_PULLDOOR
- [x] LARA_PUSH_BUTTON
- [x] LARA_PUSH_HALFBLOCK
- [x] LARA_PUSH_HALFBLOCK_END
- [x] LARA_PUSH_HALFBLOCK_START
- [x] LARA_PUSH_OBJECT
- [x] LARA_PUSHDOOR
- [x] LARA_PUSHHEAVYDOOR
- [x] LARA_THROW (used for the flare)
- [x] LARA_TRAPDOOR_OPEN
- [ ] LARA_TURN_STONE
- [x] LARA_TURN_AIRLOCK
- [x] LARA_USE_KEY
- [x] LARA_USE_OBJECT
- [x] LARA_UNDERWATER_LEVER
- [ ] LARA_UNDERWATER_PICK
- [ ] LARA_WARDROBE_*
- [ ] LARA_SWIPE_SWITCH

### Part 3: Ladders (not officially implemented yet)
- [x] LARA_LADDER_DOWN
- [x] LARA_LADDER_DOWN_START
- [x] LARA_LADDER_DOWN_STOP
- [x] LARA_LADDER_DOWN_STOP_RIGHT
- [ ] LARA_LADDER_OFFSIDE
- [ ] LARA_LADDER_OFFSIDE_MIRROR
- [ ] LARA_LADDER_OFF_BOTTOM
- [ ] LARA_LADDER_OFF_BOTTOM_MIRROR
- [x] LARA_LADDER_OFF_TOP
- [x] LARA_LADDER_OFF_TOP_MIRROR
- [x] LARA_LADDER_ONBOTTOM
- [ ] LARA_LADDER_ONTOP_BACK
- [x] LARA_LADDER_ONTOP_FRONT
- [ ] LARA_LADDER_ON_SIDE
- [ ] LARA_LADDER_ON_SIDE_MIRROR
- [x] LARA_LADDER_UP
- [x] LARA_LADDER_UP_START
- [x] LARA_LADDER_UP_STOP
- [x] LARA_LADDER_UP_STOP_LEFT
- [ ] LARA_SWIM_LADDER_ON
