### ISSUE TITLE
Object interaction (TEN-specific)

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/ten-aod_animations#6]
This is the list of all animations that exist in _TombEngine_ (either from TR1 to TR5, or new moves specific to TEN), that don't exist in _TR6: The Angel Of Darkness_.
If an animation is not in the list, it means there is no plan to remake them.

Naturally, checked ones means they have been remade, others are yet to be done.

### Part 1: Polerope
- [x] Jump up to pole stance
- [x] Pole climb up
- [x] Pole jump backwards
- [ ] Pole rotate left
- [ ] Pole rotate right
- [x] Pole slide
- [x] Pole slide to pole stance
- [x] Pole stance
- [x] Pole stance to pole slide
- [x] Pole stance to stance
- [x] Pole to fast fall
- [x] Stance to pole
- [x] Reach to pole stance

### Part 2: Rope
- [ ] Jump up to rope stance
- [ ] Reach to rope stance
- [ ] Rope climb up
- [ ] Rope rotate left
- [ ] Rope rotate right
- [ ] Rope slide
- [ ] Rope slide to rope stance
- [ ] Rope stance
- [ ] Rope stance to rope slide
- [ ] Rope stance to rope swing
- [ ] Rope swing
- [ ] Rope swing to reach 1
- [ ] Rope swing to reach 2

### Part 3: Tightrope
- [ ] Tightrope walk
- [ ] Tightrope walk to idle
- [ ] Tightrope idle
- [ ] Tightrope walk to idle careful
- [ ] Tightrope idle to walk
- [ ] Tightrope turn
- [ ] Tightrope loose left
- [ ] Tightrope recover left
- [ ] Tightrope fall left
- [ ] Tightrope loose right
- [ ] Tightrope recover right
- [ ] Tightrope fall right
- [ ] Tightrope start
- [ ] Tightrope finish

### Part 4: Swing bars
- [ ] Bars grab
- [ ] Bars swing
- [ ] Bars jump

### Part 5: Other object interaction
- [ ] Blown up by mine
- [ ] Ceiling trapdoor open
- [ ] Crowbar door open
- [ ] Crowbar pickup from the wall
- [ ] Detonator use
- [ ] Detach crowbar from the wall
- [ ] Drag body
- [ ] Dove switch
- [ ] Empty waterskin on scales puzzle
- [ ] Empty waterskin on the floor
- [ ] Fill waterskin
- [x] Flare pickup
- [ ] Flare pickup while crouching
- [ ] Flare pickup underwater
- [ ] Harp play
- [x] Jump switch
- [x] Lever switch
- [x] Light torch with flame 0 clicks high
- [x] Light torch with flame 1 clicks high
- [x] Light torch with flame 2 clicks high
- [x] Light torch with flame 3 clicks high
- [x] Light torch with flame 4 clicks high (TR5 ceiling roots)
- [ ] Look through binoculars
- [ ] Loot chest
- [ ] Loot shelf
- [ ] Mechanical scarab use
- [x] Pickup from sarcophagus
- [x] Push wall button
- [ ] Pushable block push
- [ ] Pushable block pull
- [ ] Pushable block push slip
- [ ] Pushable object push slip
- [ ] Put trident
- [ ] Radio
- [ ] Rotate Senet
- [x] Throw torch
- [ ] Train death
- [ ] Spikes death
- [ ] Underwater ceiling switch
- [ ] Underwater door open
- [x] Underwater wall kick
- [ ] Use mine detonator
- [x] Wall switch down
- [x] Wall switch up
- [x] Wall hole pickup/switch
- [x] Wall lever switch
- [ ] Wall push
- [ ] Wheel switch
- [ ] Zipline grab
- [ ] Zipline
- [ ] Zipline to fall
